### ISSUE TITLE
HGVS relationship between the transcript and the associated amino acid.

### ISSUE THREAD

**Issue by jrambla** [ga4gh-beacon/beacon-v2-Models#2]
Inherited from draft3 default schemas https://github.com/ga4gh-beacon/specification-v2/issues/59

**Comment by clauw87** [comment]
If I understand right, this is about keeping the correspondence between transcriptHGVSId - proteinHGVSIds -molecularConsequence - aminoacidChange instead of just listing them in the corresponding order, leaving possibly a NA in place when not applicable (?). If so, this then maybe could be solved then with a list of objects instead of lists of each variable separately, where each element of the list represent each transcript and will include each of this elements, NA for those not applicable (e.g leaving for aminoacidChange NA for transcripts that are non-coding, e.g having genomicFeatures class set as non-coding RNA). Would this work?

**Comment by jrambla** [comment]
@gemaroldan Could you please clarify if do you mean keeping all of the related ids together?

**Comment by jrambla** [comment]
Closing because no further comments had been provided.
