### ISSUE TITLE
Representation of Sex

### ISSUE THREAD

**Issue by pnrobinson** [ga4gh-beacon/beacon-v2-Models#82]
Comment on -- 
Beacon directly uses the (IMO preferable) [representation through an ontology term](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/08cb436eed0534e380487652279cb29597cd9d16/BEACON-V2-draft4-Model/common/commonDefinitions.json#L6), while PXF uses an [ordinal mapping](https://phenopacket-schema.readthedocs.io/en/latest/sex.html) and offers additionally a [KaryotypicSex](https://phenopacket-schema.readthedocs.io/en/latest/karyotypicsex.html) schema.

Representation of Sex via ontology terms is fine and easily convertible. Note that karyotypic sex is not an additional way of representing sex (which refers to phenotypic sex). It is not strictly necessary to represent karyotpic sex since it can be derived from representation of the karyotype in VRS/VRSATILE.

**Comment by mbaudis** [comment]
I'm aware of the widespread use of tis in genetics; in cancer genomics we think more of the "genetic sex" of the germline with potentially very different sex chromosome complement in the analyzed tissue; but genotypic sex is needed instead of gender etc.

I'll try to add this as additional attribute ASAP since it has a user base :-)

**Comment by mbaudis** [comment]
Added to the model in #86 .
